## 00. PyTorch Fundamentals 

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas 
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0+cu102


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
# Tensor 
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])