## 00. PyTorch Fundamentals 

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas 
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0+cu102


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor 
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.9941, 0.6329, 0.6797, 0.6613],
         [0.5056, 0.5549, 0.7043, 0.9305],
         [0.2005, 0.8437, 0.5126, 0.1106]]])

In [19]:
random_tensor.ndim

3

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(size=(3,3))

tensor([[0.2057, 0.6688, 0.3403],
        [0.0865, 0.0603, 0.2107],
        [0.0748, 0.5648, 0.6742]])

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors like

In [27]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three big errors with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16, # what datatype is the tensor? (eg. float32 or float16)
                              device=None, # what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tensor.dtype

torch.float16

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6935, 0.9556, 0.0425, 0.0678],
        [0.1616, 0.5392, 0.7397, 0.6850],
        [0.8436, 0.0691, 0.5030, 0.8352]])

In [36]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [37]:
# Find out details about some tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6935, 0.9556, 0.0425, 0.0678],
        [0.1616, 0.5392, 0.7397, 0.6850],
        [0.8436, 0.0691, 0.5030, 0.8352]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
    * `(3,2) @ (3,2)` won't work
    * `(2,3) @ (3,2)` will work
    * `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2,3) @ (3,2)` -> `(2,2)`
    * `(3,2) @ (2,3)` -> `(3,3)`

In [43]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [44]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
tensor @ tensor

tensor(14)

In [47]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [48]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 801 μs, sys: 185 μs, total: 986 μs
Wall time: 3.12 ms


In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 42 μs, sys: 9 μs, total: 51 μs
Wall time: 54.4 μs


tensor(14)

#### One of the most common errors in deep learning: shape errors

In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [52]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [54]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#### Finding the min, max, mean, sum etc (tensor aggregation)

In [55]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [56]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
# Find the mean - note: torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [60]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# Find the position in tensor that has minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(91)

In [65]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### Reshaping, stacking, squeezing and  unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [66]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [67]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [70]:
# Stack tensors on top of each other
x = torch.arange(1., 10.)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [71]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [72]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [73]:
# torch.permute - rearranges dimensions of target tensor in a specified order
x_original = torch.rand(size=(224,224,3))  # [height, width, color_channels]
x_original

tensor([[[0.7774, 0.2724, 0.6832],
         [0.1556, 0.2535, 0.3137],
         [0.1274, 0.9340, 0.2097],
         ...,
         [0.7270, 0.2342, 0.7520],
         [0.6687, 0.4169, 0.0667],
         [0.0740, 0.1866, 0.7825]],

        [[0.3738, 0.1097, 0.6846],
         [0.6897, 0.3203, 0.8069],
         [0.4866, 0.7224, 0.4006],
         ...,
         [0.2833, 0.7151, 0.4893],
         [0.8238, 0.1087, 0.1059],
         [0.6428, 0.3331, 0.7368]],

        [[0.4667, 0.1712, 0.5730],
         [0.7837, 0.3859, 0.4338],
         [0.5111, 0.4107, 0.7608],
         ...,
         [0.0104, 0.4681, 0.1711],
         [0.7528, 0.4101, 0.4505],
         [0.3077, 0.7978, 0.8131]],

        ...,

        [[0.0483, 0.3730, 0.9022],
         [0.6529, 0.1722, 0.2224],
         [0.8980, 0.7127, 0.6758],
         ...,
         [0.8830, 0.1167, 0.7155],
         [0.1400, 0.9547, 0.7771],
         [0.9221, 0.2757, 0.6060]],

        [[0.5734, 0.4149, 0.5862],
         [0.7989, 0.2252, 0.0593],
         [0.

In [74]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted

tensor([[[0.7774, 0.1556, 0.1274,  ..., 0.7270, 0.6687, 0.0740],
         [0.3738, 0.6897, 0.4866,  ..., 0.2833, 0.8238, 0.6428],
         [0.4667, 0.7837, 0.5111,  ..., 0.0104, 0.7528, 0.3077],
         ...,
         [0.0483, 0.6529, 0.8980,  ..., 0.8830, 0.1400, 0.9221],
         [0.5734, 0.7989, 0.5957,  ..., 0.3003, 0.7513, 0.6717],
         [0.1011, 0.5921, 0.0061,  ..., 0.2569, 0.1882, 0.2390]],

        [[0.2724, 0.2535, 0.9340,  ..., 0.2342, 0.4169, 0.1866],
         [0.1097, 0.3203, 0.7224,  ..., 0.7151, 0.1087, 0.3331],
         [0.1712, 0.3859, 0.4107,  ..., 0.4681, 0.4101, 0.7978],
         ...,
         [0.3730, 0.1722, 0.7127,  ..., 0.1167, 0.9547, 0.2757],
         [0.4149, 0.2252, 0.7700,  ..., 0.5450, 0.1778, 0.8408],
         [0.9811, 0.1132, 0.7150,  ..., 0.6460, 0.6490, 0.1718]],

        [[0.6832, 0.3137, 0.2097,  ..., 0.7520, 0.0667, 0.7825],
         [0.6846, 0.8069, 0.4006,  ..., 0.4893, 0.1059, 0.7368],
         [0.5730, 0.4338, 0.7608,  ..., 0.1711, 0.4505, 0.

In [75]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [76]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0,0]

tensor([1, 2, 3])

In [83]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [84]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [85]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [88]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [89]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [91]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [92]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [97]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default 
# datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [98]:
array.dtype

dtype('float64')

In [99]:
tensor.dtype

torch.float32

In [100]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [101]:
# Change the value of array , what will this do to a `tensor`?
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [102]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [103]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [104]:
numpy_tensor.dtype

dtype('float32')

In [105]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [106]:
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

### Reproducibility (trying to take the random out of random)

In short, how our neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

Reduce the randomness in neural networks and PyTorch comes a concept of a **random seed**.

Essentially, what random seed does is "flavour" the randomness.

In [110]:
torch.rand(3,3)

tensor([[0.1393, 0.2685, 0.5135],
        [0.9652, 0.0531, 0.8174],
        [0.0384, 0.7656, 0.8260]])

In [111]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3603, 0.8338, 0.8727, 0.6785],
        [0.8222, 0.0841, 0.3285, 0.9294],
        [0.2416, 0.4653, 0.1722, 0.5072]])
tensor([[0.4043, 0.0422, 0.9102, 0.5742],
        [0.8820, 0.9258, 0.4819, 0.4590],
        [0.3514, 0.6264, 0.8441, 0.1475]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [112]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

In [115]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

In [116]:
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://docs.pytorch.org/docs/2.12/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)!

#### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... see this post for what options to get - https://timdettmers.com/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/

In [118]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


#### 2. Check for GPU access with PyTorch 

In [119]:
# Check for GPU access with PyTorch
import torch

torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/2.12/notes/cuda.html

E.g. run on GPU if available else default to CPU

In [120]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [121]:
# Count the number of devices
torch.cuda.device_count()

0

#### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [123]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [124]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

#### 4. Moving tensors back to the CPU

In [125]:
# If tensor is not GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [126]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [127]:
tensor_on_gpu

tensor([1, 2, 3])