## 00. PyTorch Fundamentals 

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas 
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0+cu102


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor 
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.3551, 0.0832, 0.4926, 0.2188],
         [0.4987, 0.6899, 0.9043, 0.4890],
         [0.3927, 0.8856, 0.8294, 0.0310]]])

In [19]:
random_tensor.ndim

3

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(size=(3,3))

tensor([[0.3079, 0.1930, 0.1814],
        [0.5889, 0.1180, 0.2391],
        [0.6371, 0.3361, 0.7263]])

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors like

In [27]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three big errors with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16, # what datatype is the tensor? (eg. float32 or float16)
                              device=None, # what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tensor.dtype

torch.float16

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8283, 0.7900, 0.2562, 0.3503],
        [0.4230, 0.9308, 0.2198, 0.1767],
        [0.2147, 0.8859, 0.0010, 0.4089]])

In [42]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [43]:
# Find out details about some tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8283, 0.7900, 0.2562, 0.3503],
        [0.4230, 0.9308, 0.2198, 0.1767],
        [0.2147, 0.8859, 0.0010, 0.4089]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [48]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [49]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [52]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [53]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
    * `(3,2) @ (3,2)` won't work
    * `(2,3) @ (3,2)` will work
    * `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2,3) @ (3,2)` -> `(2,2)`
    * `(3,2) @ (2,3)` -> `(3,3)`

In [71]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [56]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
tensor @ tensor

tensor(14)

In [58]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [60]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.14 ms, sys: 26 μs, total: 1.17 ms
Wall time: 1.65 ms


In [61]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 419 μs, sys: 272 μs, total: 691 μs
Wall time: 929 μs


tensor(14)

#### One of the most common errors in deep learning: shape errors

In [72]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [73]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [79]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [80]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [84]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#### Finding the min, max, mean, sum etc (tensor aggregation)

In [89]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [86]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [87]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [93]:
# Find the mean - note: torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [94]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [99]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [100]:
# Find the position in tensor that has minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [101]:
x[0]

tensor(1)

In [102]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [103]:
x[9]

tensor(91)

In [104]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### Reshaping, stacking, squeezing and  unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [121]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [123]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [125]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [133]:
# Stack tensors on top of each other
x = torch.arange(1., 10.)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [137]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [140]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [141]:
# torch.permute - rearranges dimensions of target tensor in a specified order
x_original = torch.rand(size=(224,224,3))  # [height, width, color_channels]
x_original

tensor([[[0.0445, 0.0266, 0.6561],
         [0.0562, 0.9645, 0.7983],
         [0.6468, 0.5920, 0.2599],
         ...,
         [0.3972, 0.0271, 0.2441],
         [0.0460, 0.6933, 0.7942],
         [0.5524, 0.1008, 0.6970]],

        [[0.4695, 0.6671, 0.7133],
         [0.1168, 0.8236, 0.8946],
         [0.0327, 0.2759, 0.2646],
         ...,
         [0.2902, 0.6255, 0.1406],
         [0.4723, 0.2885, 0.1462],
         [0.3100, 0.1208, 0.1579]],

        [[0.9051, 0.5950, 0.8716],
         [0.4402, 0.0693, 0.3932],
         [0.5580, 0.3196, 0.6262],
         ...,
         [0.8654, 0.8777, 0.3775],
         [0.4706, 0.7576, 0.1616],
         [0.8316, 0.7777, 0.2319]],

        ...,

        [[0.6207, 0.3454, 0.4947],
         [0.0432, 0.3433, 0.1092],
         [0.6308, 0.5060, 0.3920],
         ...,
         [0.2744, 0.6408, 0.2194],
         [0.1815, 0.0929, 0.2900],
         [0.7844, 0.4839, 0.3351]],

        [[0.3444, 0.3566, 0.8444],
         [0.5846, 0.5279, 0.6511],
         [0.

In [142]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted

tensor([[[0.0445, 0.0562, 0.6468,  ..., 0.3972, 0.0460, 0.5524],
         [0.4695, 0.1168, 0.0327,  ..., 0.2902, 0.4723, 0.3100],
         [0.9051, 0.4402, 0.5580,  ..., 0.8654, 0.4706, 0.8316],
         ...,
         [0.6207, 0.0432, 0.6308,  ..., 0.2744, 0.1815, 0.7844],
         [0.3444, 0.5846, 0.5952,  ..., 0.1410, 0.0119, 0.6309],
         [0.1663, 0.3436, 0.6357,  ..., 0.8815, 0.3099, 0.7829]],

        [[0.0266, 0.9645, 0.5920,  ..., 0.0271, 0.6933, 0.1008],
         [0.6671, 0.8236, 0.2759,  ..., 0.6255, 0.2885, 0.1208],
         [0.5950, 0.0693, 0.3196,  ..., 0.8777, 0.7576, 0.7777],
         ...,
         [0.3454, 0.3433, 0.5060,  ..., 0.6408, 0.0929, 0.4839],
         [0.3566, 0.5279, 0.1812,  ..., 0.2817, 0.4881, 0.3379],
         [0.3147, 0.7860, 0.2636,  ..., 0.3208, 0.7128, 0.2164]],

        [[0.6561, 0.7983, 0.2599,  ..., 0.2441, 0.7942, 0.6970],
         [0.7133, 0.8946, 0.2646,  ..., 0.1406, 0.1462, 0.1579],
         [0.8716, 0.3932, 0.6262,  ..., 0.3775, 0.1616, 0.

In [143]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
